ProjetoQuiosque/urls.py
from django.conf.urls import url
from django.contrib import admin
from core import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login
from django.contrib.auth.views import logout





urlpatterns =   [
	url(r'^$', views.index, name="index"),
    url(r'^resultadobuscar/$', views.resultadobuscar, name="resultadobuscar"),
    url(r'^arte_detalhes/$',views.arte_detalhes,name="arte_detalhes"),
    url(r'^gerenciararte/$',views.gerenciararte,name="gerenciararte"),
    url(r'^carrinho/$',views.carrinho,name="carrinho"),
    url(r'^editarte/$',views.editarte,name="editarte"),
    url(r'^enviarArte/$',views.enviarArte,name="enviarArte"),
    url(r'^editdadospessoais/$',views.editdadospessoais,name="editdadospessoais"),
    url(r'^finalizarcompra/$',views.finalizarcompra,name="finalizarcompra"),
    url(r'^usuario/$', views.usuario, name="usuario"),
    url(r'^sobre/$', views.sobre, name="sobre"),
    url(r'^login/$', login, {'template_name': 'login.html'}, name="login"),
    url(r'^sair/$', logout, {'next_page': '/'}, name="logout"),
    url(r'^admin/', admin.site.urls),




]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm

class cartaoCredito(models.Model):
    numero = models.CharField('Número de cartão', max_length=16, blank=True, null=True)
    codSeguranca = models.CharField('Código de segurança', max_length=3, null=True)
    nomeCartao = models.CharField('Nome', max_length=40, null=True)
    dataValidade = models.DateField('Data Vencimento')


class Usuario(models.Model):
    cpfCnpj = models.CharField('CPF', max_length=11, null=True)
    cartao = models.ManyToManyField(cartaoCredito, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):

        return self.user.first_name

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


class Categoria(models.Model):
    categoria = models.CharField("Categoria da arte", max_length=20, null=True)

    def __str__(self):
        return self.categoria

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

class Arte(models.Model):
    descricao = models.CharField("Descrição", max_length=100, blank=True, null=True)
    dataCadastro = models.DateField('Data de cadastro', auto_now_add=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    preco = models.FloatField("Preço", blank=True, null=True)
    imagem_principal = models.ImageField(upload_to='img/imagensArtes/', verbose_name='Imagem da Arte', blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = 'Arte'
        verbose_name_plural = 'Artes'

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuario
from .models import Arte
from .models import Categoria
from .models import cartaoCredito
from django.contrib.auth.models import User

class autenticacao(forms.Form):
	email = forms.CharField()
	senha = forms.CharField(widget=forms.PasswordInput())
	def __init__(self, arg):
		super(au, self).__init__()
		self.arg = arg

class UserModelForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'username']

class UsuarioModelForm(forms.ModelForm):

	class Meta:
		model = Usuario
		fields = ['cpfCnpj']

class ArteModelForm(forms.ModelForm):
    class Meta:
        model = Arte
        fields = '__all__'

class EditArteModelForm(forms.ModelForm):
	class Meta:
		model = Arte
		fields = ['descricao', 'preco']

class CartaoModelForm(forms.ModelForm):
	class Meta:
		model = cartaoCredito
		fields = ['numero', 'codSeguranca', 'nomeCartao', 'dataValidade']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control mr-sm-2'
	    })

core/views.py
from django.shortcuts import render
from .models import Arte
from .models import Usuario
from .models import Categoria
from .forms import CartaoModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserModelForm
from .forms import UsuarioModelForm
from .forms import ArteModelForm
from .forms import EditArteModelForm
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.
def index(request):
	Artes = Arte.objects.all().order_by('-id')[:3]


	formUser = UserModelForm(request.POST or None)
	formCPF = UsuarioModelForm(request.POST or None)
	form = UserCreationForm(request.POST or None)
	context = {
		'formUser': formUser,
		'formCPF': formCPF,
		'form': form
	}
	if request.method == 'POST':
		if form.is_valid() and formUser.is_valid():
			usuario_post = UserCreationForm(request.POST)
			usuario = usuario_post.save(commit=False)
			usuario.first_name = formUser.cleaned_data['first_name']
			usuario.last_name = formUser.cleaned_data['last_name']
			usuario.email = formUser.cleaned_data['email']
			usuario.save()
			if formCPF.is_valid():
				cpf_post = UsuarioModelForm(request.POST)
				cpf = cpf_post.save(commit=False)
				cpf.user  = usuario
				cpf.save()
	return render (request, 'index.html', context)


def resultadobuscar(request):
	categoria = Categoria.objects.all()
	page = request.GET.get('page', 1)


	if request.method == 'GET':
		if 'nomeget' in request.GET:
			nomeget=request.GET.get("nomeget")
		else:
			nomeget=""
		if 'categoriaget' in request.GET and request.GET.get("categoriaget")!="Escolha a categoria":
			categoriaget=request.GET.get("categoriaget")
		else:
			categoriaget=Categoria.objects.values_list('id')

		artest =  Arte.objects.filter(descricao__icontains=nomeget, categoria__id__in=categoriaget)


		paginator = Paginator(artest, 12)
	else:
		artest = Arte.objects.all()
		paginator = Paginator(artest, 12)
	try:
		artes = paginator.page(page)
	except 	PageNotAnInteger:
		artes = paginator.page(1)
	except EmptyPage:
		artes = paginator.page(paginator.num_pages)



	context = {
		'categoria': categoria,
		'artes': artes,
		'nomeget' : nomeget
	}

	return render(request, 'ResultadoBuscar.html', context)

def arte_detalhes(request):
	id_arte = request.GET.get("id")
	artes = Arte.objects.get(id = id_arte)
	context = {
	'artes': artes,
	}
	return render(request,'arte_detalhes.html', context)


@login_required(login_url='login')
def gerenciararte(request):
	id_usuario = request.user
	usuario = Usuario.objects.get(user=id_usuario)
	artes = Arte.objects.filter(usuario = usuario)
	page = request.GET.get('page', 1)
	paginator = Paginator(artes, 8)

	if request.method == 'GET':
		if 'op' in request.GET:
			if request.GET.get("op") == 'remover':
				if 'id' in request.GET:
					id_arte = request.GET.get("id")
					arte = Arte.objects.get(id = id_arte)
					arte.delete()

	try:
		artes = paginator.page(page)
	except 	PageNotAnInteger:
		artes = paginator.page(1)
	except EmptyPage:
		artes = paginator.page(paginator.num_pages)

	context = {
		'artes': artes,
		'usuario': usuario,

	}

	return render(request, 'gerenciararte.html', context)

def carrinho(request):

	lista_artes = []
	total = 0
	if 'artes' in request.session:
		lista_artes = request.session['artes']

	if request.method == 'GET':
		if 'op' in request.GET:
			if request.GET.get("op") == 'adicionar':
				if 'id' in request.GET:
					id_arte = request.GET.get("id")
					contador = 0
					for arte in lista_artes:
						if arte[0] == id_arte:
							return redirect('/carrinho')

					'''id_arte = request.GET.get("id")'''
					arte = Arte.objects.get(id=id_arte)
					lista_artes.append([id_arte, arte.descricao, arte.preco, arte.imagem_principal.url])
					request.session['artes'] = lista_artes
					return redirect('/carrinho?total={}'.format(totalCarrinho(request)))
			elif request.GET.get("op") == 'remover':
				if 'id' in request.GET:
					id_arte_remover = request.GET.get("id")
					cont = 0
					for arte in lista_artes:
						if arte[0] == id_arte_remover:
							del lista_artes[cont]
						cont+=1
					request.session['artes'] = lista_artes
					return redirect('/carrinho?total={}'.format(totalCarrinho(request)))
	total = totalCarrinho(request)
	context = {
		'total': total
	}
	return render(request, 'carrinho.html', context)


def totalCarrinho(req):
	if 'artes' in req.session:
		lista_artes = req.session['artes']
		total = 0
		for arte in lista_artes:
			total += arte[2]
	else:
		total = 0
	return total

def todasAsArtes(req):
	if 'artes' in req.session:
		lista_artes = req.session['artes']
	return lista_artes

@login_required(login_url='login')
def finalizarcompra(request):
	id_usuario = request.user
	usuario = Usuario.objects.get(user=id_usuario)
	form = CartaoModelForm(request.POST or None)
	lista_artes = todasAsArtes(request)
	vlTotal = totalCarrinho(request)
	nomesArtes = ""

	context = {
		'form': form,
		'usuario': usuario,
		'lista_artes': lista_artes,
		'vlTotal': vlTotal,
	}

	if request.method == 'POST':
		if form.is_valid():
			for artes in lista_artes:
				nomesArtes = nomesArtes + '\n- ' + artes[1]

			cartao = form.save(commit=False)
			cartao.usuario = usuario
			cartao.save()
			email = usuario.user.email
			nome = usuario.user.first_name
			nome2 = usuario.user.last_name
			request.session['artes'] = []
			mensagem_completa = 'Olá, {0} {1}!\nVocê acaba de adquirir em nosso site os direitos de uso da(s) seguinte(s) arte(s): \n\n{2}\n\nValor total: R$ {3} \n\n\nSe não foi você quem fez essa compra, quem sabe morre'.format(nome, nome2, nomesArtes, vlTotal)
			send_mail('Confirmação de compra | Quiosque Online', mensagem_completa, settings.DEFAULT_FROM_EMAIL, [email])
			return redirect('/gerenciararte')
	request.session['artes'] = []
	return render(request, 'finalizarcompra.html', context)

@login_required(login_url='login')
def editdadospessoais(request):
	id_usuario = request.user
	usuario = Usuario.objects.get(user=id_usuario)
	context = {
		'usuario': usuario,
	}
	return render(request, 'editdadospessoais.html', context)

@login_required(login_url='login')
def editarte(request):
	if request.method == 'POST':
		id_arte = request.POST.get("id")
		arte = Arte.objects.get(id = id_arte)
		formEditArte = EditArteModelForm(request.POST or None, instance = arte)
		if formEditArte.is_valid():
			arte.save()
			return redirect('/gerenciararte')
	formEditArte = EditArteModelForm()
	if request.method == 'GET':
		id_arte = request.GET.get("id")
		arte = Arte.objects.get(id = id_arte)
	context = {
		'formEditArte': formEditArte,
		'arte': arte,
	}
	return render(request, 'editarte.html', context)

@login_required(login_url='login')
def enviarArte(request):
	categorias = Categoria.objects.all()
	id_usuario = request.user
	usuario = Usuario.objects.get(user=id_usuario)

	if request.method == 'POST':
		formArte = ArteModelForm(request.POST, request.FILES)
		if formArte.is_valid():
			arte = formArte.save(commit=False)
			arte.usuario = usuario
			arte.save()
			return redirect('/gerenciararte')

	formArte = ArteModelForm()
	context = {
		'formArte' : formArte,
		'categorias' : categorias

	}
	return render( request, 'enviarArte.html', context)


@login_required(login_url='login')
def usuario (request):
	id_usuario = request.user
	usuario = Usuario.objects.get(user=id_usuario)
	context = {
		'usuario': usuario,
	}
	return render(request, 'usuario.html', context)

def sobre(request):
	return render( request, 'sobre.html')

core/templates/ResultadoBuscar.html
{% extends "base.html" %}
{% load static %}


{% block titulo %}
Resultado da Busca | {{ block.super }}
{% endblock %}


{% block conteudo %}


<div class="container">

  <br>
  <div class="col-md-3">


  </div>
</hr>
</hr>

</div>
<section id="portfolio">
  <div class="container wow fadeInUp">
    <div class="row">
      <div class="col-md-12">
        <h3 class="section-title">Resultado da Pesquisa para "{{nomeget}}"</h3>
        <div class="section-title-divider"></div>
        <form class="align-center">
          <div class="form-row align-items-center" method="get" action="{% url 'resultadobuscar' %}">
            <div class="col-auto">
              <select  name="categoriaget" class="form-control">
                <option selected>Escolha a categoria</option>
                {% for cat in categoria %}
                <option value="{{cat.id}}">{{cat.categoria}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-auto">
              <button type="submit" class="btn btn-danger"><b>FILTRAR</b></button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <br>

    <div class="row">
      {% for arte in artes %}
      <div class="col-md-3">
        <a class="portfolio-item" style="background-image: url({{arte.imagem_principal.url}});" href="{% url 'arte_detalhes' %}?id={{arte.id}}">
          <div class="details">
            <h4>{{arte.descricao}}</h4>
          </div>
        </a>
      </div>
      {% empty %}
      <p>Nenhuma arte cadastrada</p>

      {% endfor %}

    </div>

    <ul class="pagination justify-content-center">
      <li class="page-item">
        {% if artes.has_previous %}
        <a class="page-link" href="?page={{ artes.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
        {% endif %}
      </li>
      {% for ar in artes.paginator.page_range %}
      {% if artes.number == ar %}​
      <li class="page-item active">
        <a class="page-link"><span>{{ ar }}<span class="sr-only">(current)</span></span></a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ ar }}">{{ ar }}</a>
      </li>
      {% endif %}
      {% empty %}
      <div class="alert alert-primary" role="alert">
        Nenhuma arte cadastrada.
      </div>
      {% endfor %}
      {% if artes.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ artes.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>

      {% endif %}
    </ul>
  </div>
  </section>


  {% endblock %}

core/templates/arte_detalhes.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
Detalhe da Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}

<section id="portfolio">
  <div class="container wow fadeInUp">
    <div class="row">
      <div class="col-md-12">
        <h3 class="section-title">Detalhes da arte</h3>
        <div class="section-title-divider"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <br>
        <img class="img-fluid img-thumbnail rounded float-left" src="{{artes.imagem_principal.url}}" alt="" width="700" hspace="15"/>
      </div>
      <div class="col-md-3">
      </br>
        <h3><b>Nome da Arte:</b></h3><h2>{{ artes.descricao }}</h2>
        <h3><b>Data de Cadastro:</b></h3><h2>{{ artes.dataCadastro }}</h2>
        <h3><b>Autor:</b></h3><h2>{{ artes.usuario.user.first_name }}</h2>
        <h3><b>Preço:</b></h3><h2>R$ {{artes.preco}}0</h2></br>
        <a href="{% url 'carrinho' %}?op=adicionar&id={{artes.id}}"><button type="button" class="btn btn-danger">Adicionar ao Carrinho <i class="fas fa-shopping-cart"></i></button></a>
      </div>
    </div>
</section>
​{% endblock %}

core/templates/dados_pessoais.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
Detalhe da Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}

<h1 class="centered">Dados Pessoais</h1><br />
<hr/>
<div class="container">​
    <div class="row mt">
        <form>

        </form>
        ​​   
    </div>
</div>
 ​​

​{% endblock %}

core/templates/edit_dados_pessoais.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
Detalhe da Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}

<h1 class="centered">Dados Pessoais</h1><br />
<hr/>
<div class="container">​
    <div class="row mt">
        <!-- Para concluir, conferir site da gearbest -->
        <legend>Editar Dados Pessoais</legend>

    </div>
</div>


​{% endblock %}

core/templates/editarte.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
Editar Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}


<section id="portfolio">
  <div class="container wow fadeInUp">
    <div class="row">
      <div class="col-md-12">
        <br>
        <h3 class="section-title">Editar</h3>
        <div class="section-title-divider"></div>
      </div>
        <div class="col-md-7">
          <img class="img-fluid img-thumbnail rounded float-left" src="{{arte.imagem_principal.url}}" alt="{{arte.descricao}}" width="700" hspace="15"/>
          </div>
          <div class="col-md-3">
            <form action="{% url 'editarte' %}" method="post" >
              {% csrf_token %}
                <h3><b>{{arte.descricao}}</b></h3>
                <div class="form-group">
        					<input type="text" class="form-control" name="descricao" maxlength="100" id="id_descricao" placeholder="Novo Nome"/>
        				</div>
              <div class="form-group">
                <h3><b>Preço: R${{arte.preco}}0</b></h3>
                <div class="form-group">
        					<input type="number" class="form-control" name="preco" step="any" id="id_preco" placeholder="Novo Preço"/>
        				</div>
              </div>
              {% if arte.id %}
              <input type="hidden" name="id" value="{{ arte.id }}" />
              {% endif %}
              <input class = "btn btn-danger" type="submit" value="Enviar" />
            </form>
        </div>
      <div class="col-md-3">
      </div>
    </div>
  </div>
</section>

​​

​{% endblock %}

core/templates/editdadospessoais.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
Detalhe da Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}

<section id="portfolio">

    <div class="container wow fadeInUp">
        <div class="row">
            <div class="col-md-12">
              <h3 class="section-title">Editar Dados</h3>
              <div class="section-title-divider"></div>
              <p class="section-description"></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div> <!--Utilizado para centralizar a segunda DIV-->
            <div class="col-md-4">
                <form action="{% url 'editdadospessoais' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_first_name"><b>Nome</b></label>
                        <input type="text" class="form-control" name="first_name" maxlength="30" id="id_first_name" autofocus placeholder="{{ user.first_name }}" />
                    </div>
                    <div class="form-group">
                        <label for="id_last_name"><b>Sobrenome</b></label>
                        <input type="text" class="form-control" name="last_name" maxlength="30" id="id_last_name" placeholder="{{ user.last_name }}"/>
                    </div>
                    <div class="form-group">
                        <label for="id_email"><b>Email</b></label>
                        <input type="email" class="form-control" name="email" maxlength="254" id="id_email" placeholder="{{ user.email }}"/>
                    </div>
                    <div class="form-group">
                        <label for="id_cpfCnpj"><b>CPF</b></label>
                        <input type="text" class="form-control" name="cpfCnpj" maxlength="11" id="id_cpfCnpj" required placeholder="{{ usuario.cpfCnpj }}"/>
                    </div>
                    <div class="form-group">
                        <label for="id_username"><b>Usuário</b></label>
                        <input type="text" class="form-control" name="username" maxlength="150" id="id_username" required placeholder="{{ user }}"/>
                    </div>
                    <!--<div class="form-group">
                        <label for="id_password1"><b>Senha</b></label>
                        <input type="password" class="form-control" name="password1" id="id_password1" required placeholder="Senha"/>
                    </div>
                    <div class="form-group">
                        <label for="id_password2"><b>Confirmar Senha</b></label>
                        <input type="password" class="form-control" name="password2" id="id_password2" required placeholder="Confirmar Senha"/>
                    </div>-->
                    <p align="right"><a href="#" role="button" aria-pressed="true"><input type="submit" name="registro" class="btn btn-outline-danger" value="Salvar alterações"></a></p>
                </form>      
            </div>
            <div class="col-md-4"></div><!--Utilizado para centralizar a segunda DIV-->
        </div>
  </div>
</section>


​{% endblock %}

core/templates/enviarArte.html
{% extends "base.html" %}
{% load static%}

{% block titulo %}
Enviar Arte | {{ block.super }}
{% endblock %}

{% block conteudo %}
<section id="portfolio">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h3 class="section-title">Adicionar uma nova Arte</h3>
				<div class="section-title-divider"></div>
			</div>
		</div>

		<div class="row mt">


			{% for field in formArte %}
			{% if field.errors %}
			<div class="alert alert-danger">
				<p>{{ field.label }}:	{{ field.errors }}</p>
			</div>
			{% endif %}
			{% endfor %}
			<form action="{% url 'enviarArte' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_descricao"><b>NOME DA ARTE</b></label>
					<input type="text" class="form-control" name="descricao" id="id_descricao" maxlength="100" placeholder="Nome da arte">
				</div>
				<div class="form-group">
					<label for="id_preco"><b>VALOR</b></label>
					<input type="number" class="form-control" name="preco" id="id_preco" step="any" placeholder="Valor da arte">
				</div>
				<div class="form-group">
					<label for="id_imagem_principal"><b>ARQUIVO DA IMAGEM</b></label>
					<input type="file" class="form-control-file" name="imagem_principal" id="id_imagem_principal" placeholder="Valor da arte">
				</div>
				<div class="form-group">
					<label for="id_categoria"><b>CATEGORIA DA IMAGEM</b></label>
					<select class="form-control" name="categoria" id="id_categoria">
						<option value="">Escolha uma categoria</option>
						{% for cat in categorias %}
						<option value="{{cat.id}}">{{cat.categoria}}</option>
						{% endfor %}
					</select>
				</div>
				<input class = "btn btn-danger" type="submit" value="Enviar" />
			</form>

		</div>
	</div>
</section>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% load static%}
{% block titulo %}
Página Inicial | {{ block.super }}
{% endblock %}
{% block conteudo %}
<section id="hero">
	<div class="hero-container">
		<div class="wow fadeIn">
			<div class="hero-logo">
				<img class="" src="{% static '/img/logo.png' %}" alt="Quiosque" width="300px">
			</div>

			<h1>Bem vindo ao QUIOSQUE ONLINE</h1>
			<h2>Faça seu Cadastro ou Login</h2>

			<div class="actions">
				{% if user.is_authenticated %}
				<a href="{% url 'resultadobuscar' %}" class="btn-get-started">ACESSAR ARTES</a>
				{% else %}
				<a href="#" class="btn-get-started" data-toggle="modal" data-target="#register-modal">FAZER CADASTRO</a>
				<a href="{% url 'login' %}" class="btn-services">LOGIN</a>
				{% endif %}
			</div>
		</div>
	</div>
</section>

<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content loginmodal-container">
			<h1>
				Crie sua conta
			</h1>
			<div class="section-title-divider"></div>
			<br>
			{% for field in formUser %}
			{% if field.errors %}
			<div class="alert alert-danger">
				{{ field.errors }}
				{{ field.label}}
			</div>
			{% endif %}
			{% endfor %}

			<form action="{% url 'index' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_first_name"><b>NOME</b></label>
					<input type="text" class="form-control" name="first_name" maxlength="30" id="id_first_name" autofocus placeholder="Nome" />
				</div>
				<div class="form-group">
					<label for="id_last_name"><b>SOBRENOME</b></label>
					<input type="text" class="form-control" name="last_name" maxlength="30" id="id_last_name" placeholder="Sobrenome"/>
				</div>
				<div class="form-group">
					<label for="id_email"><b>EMAIL</b></label>
					<input type="email" class="form-control" name="email" maxlength="254" id="id_email" placeholder="exemplo@gmail.com"/>
				</div>
				<div class="form-group">
					<label for="id_cpfCnpj"><b>CPF</b></label>
					<input type="text" class="form-control" name="cpfCnpj" maxlength="11" id="id_cpfCnpj" required placeholder="CPF"/>
				</div>
				<div class="form-group">
					<label for="id_username"><b>USUÁRIO</b></label>
					<input type="text" class="form-control" name="username" maxlength="150" id="id_username" required placeholder="Usuário"/>
				</div>
				<div class="form-group">
					<label for="id_password1"><b>SENHA</b></label>
					<input type="password" class="form-control" name="password1" id="id_password1" required placeholder="Senha"/>
				</div>
				<div class="form-group">
					<label for="id_password2"><b>CONFIRMAR SENHA</b></label>
					<input type="password" class="form-control" name="password2" id="id_password2" required placeholder="Confirmar Senha"/>
				</div>
				<input type="submit" name="registro" class="login loginmodal-submit" value="Criar Conta">
			</form>
		</div>
	</form>
	<div class="login-help">
		<a href="#"> Registrar-se </a>
	</div>
</div>
</div>
</div>




{% endblock %}